---
abstract: 'Pretty-print data structure as YAML'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Format-Pretty-YAML
requires:
  SHARYANTO::String::Util: 0
  YAML::Syck: 0
  YAML::Tiny::Color: 0.02
  perl: 5.010001
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Data-Format-Pretty-YAML
  homepage: https://metacpan.org/release/Data-Format-Pretty-YAML
  repository: git://github.com/sharyanto/perl-Data-Format-Pretty-YAML.git
version: 0.06
